title: "Girsl Who Code @ Berkeley"
remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/gwc_logo.png"
aux_links:
  "Visit us on Facebook":
    - "//facebook.com/gwcberkeley/"
aux_links_new_tab: true
